name: Build and Deploy # 工作流名称
on: # 指定触发 workflow 的条件，通常是某些事件。（main分支push时触发）
    push:
        branches:
            - main
jobs: # workflow 文件的主体是jobs字段，表示要执行的一项或多项任务。
    build-and-deploy:
        runs-on: ubuntu-latest # 指定运行所需要的虚拟机环境，必填字段
        steps:
            - name: Checkout  ️
              uses: actions/checkout@v2.3.1

            - name: lock npm version
              uses: actions/setup-node@v3
              with:
                  node-version: 18.17.1

            - name: Install and Build
              run: |
                  npm i -g pnpm
                  pnpm run init
                  pnpm run docs:build
              env:
                  NODE_OPTIONS: '--max_old_space_size=4096'

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.3
              with:
                  BRANCH: gh-pages
                  FOLDER: docs/.vuepress/dist
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} #生成及使用方法 自行百度
